// Generated by https://quicktype.io

export interface Movie {
  type:           Type;
  adult:          boolean;
  id:             number;
  original_title: string;
  popularity:     number;
  video:          boolean;
}

export enum Type {
  Movie = "movie",
}
